blank_issues_enabled: false
contact_links:
  - name: Mergington High School IT Support
    url: mailto:support@mergington.edu
    about: Please contact IT Support for urgent issues or technical problems with the system.