name: Manage Student Registration
description: Register or unregister students for activities
title: "[STUDENT REGISTRATION]: "
labels: ["registration", "student"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Student Registration Management Form
        Use this form to request student registration changes that you cannot perform through the regular interface.

  - type: dropdown
    id: action_type
    attributes:
      label: Action Type
      description: What would you like to do?
      options:
        - Register a student for an activity
        - Unregister a student from an activity
        - Transfer a student from one activity to another
        - Register multiple students (batch registration)
        - Unregister multiple students (batch unregistration)
    validations:
      required: true

  - type: input
    id: activity_name
    attributes:
      label: Activity Name
      description: The name of the activity
      placeholder: "Chess Club"
    validations:
      required: true

  - type: input
    id: student_email
    attributes:
      label: Student Email
      description: Email address of the student (for single student actions)
      placeholder: "student@mergington.edu"
    validations:
      required: false

  - type: input
    id: target_activity
    attributes:
      label: Target Activity (for transfers only)
      description: If transferring a student, enter the destination activity
      placeholder: "Strategy Games Club"
    validations:
      required: false

  - type: textarea
    id: student_list
    attributes:
      label: Student List (for batch actions)
      description: For batch registrations/unregistrations, enter one student email per line
      placeholder: |
        student1@mergington.edu
        student2@mergington.edu
        student3@mergington.edu
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: Reason for Request
      description: Why is this change needed? (especially if it can't be done through the regular interface)
      placeholder: "The student missed the registration deadline but has permission to join."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Request Priority
      description: How urgent is this request?
      options:
        - Low (Complete within a week)
        - Medium (Complete within 2-3 days)
        - High (Complete within 24 hours)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## What happens next?
        
        Our technical team will review this request and make the requested changes to student registrations. You'll be notified when the changes have been completed.